# Generated by Django 2.2 on 2019-04-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topup',
            old_name='account_number',
            new_name='topup_account_number',
        ),
    ]
